DES-117 | Implement new color palette API
PaackEng/paack-ui pull request #262
Opened 2021-07-15 00:48 UTC by renanpvaz

<img src="https://user-images.githubusercontent.com/14297772/125710662-d82b764e-4e50-4ef8-9897-551307f5022c.png" width="500">

#### :thinking: What?

Our new shiny color Palette and also:
- New terminology:
  - Tone -> Hue
  - Brightness -> Shade
  - primary -> blue
  - success -> green
  - danger -> red
  - warning -> yellow
- Color shorthands: `blue`, `red`, `gray`, `yellow` and `green`
- Attribute shorthands: `toBackgroundColor`, `toFontColor` and `toBorderColor`
- Updated showcase

#### :man_shrugging: Why?

Because it's finally time

#### :pushpin: Jira Issue

[DES-117](https://paacklogistics.atlassian.net/browse/DES-117)

#### :no_good: Blocked by

Nothing.

#### :clipboard: Pending

- [ ] Update other components' APIs to use the new palette

### :fire: Extra

This is optional, but you can add any other useful information that would not fit in the other topics.

2021-07-15 07:30 UTC, miguelcoba approved these changes

2021-07-15 12:36 UTC, kress95 approved these changes

2021-07-15 13:59 UTC, PedroHLC commented on src/UI/Palette/V2.elm
> +setContrasting enabled (Color prop opt) =
I would rather drop this. I don't recall any use-case for it. It is leftover from V1.

2021-07-15 13:59 UTC, PedroHLC commented on src/UI/Palette/V2.elm
> +toBorderColor : Color -> Element.Attribute msg
great shortcuts (Font/Border/Background)!

2021-07-16 15:03 UTC, PedroHLC requested changes

2021-07-16 15:03 UTC, PedroHLC commented on elm.json
>  {
I think you accidentally prettifyed `elm.json`, the elm-compiler does not like handmade changes to it...

2021-07-16 16:38 UTC, PedroHLC approved these changes

2021-07-16 16:45 UTC, merged