Expose DateInput module
PaackEng/paack-ui pull request #309
Opened 2021-09-29 14:47 UTC by gregziegan

#### :thinking: What?

Expose some functions and types from the `DateInput` module.

#### :man_shrugging: Why?

It's currently impossible to use the remote date-based filters with the Table modules as their `DateInput -> msg` arguments require an external msg definition like `FilterDateFieldBy (Maybe DateInput)` and `FilterDateFieldBy (Maybe UI.Internal.DateInput)` is impossible since `UI.Internal` is purposely not exposed.

#### :pushpin: Jira Issue

Not tracked.

#### :no_good: Blocked by

Nothing.

#### :clipboard: Pending

- [ ] Add tests, not sure what kinds of tests you all would like
- [ ] Expose more functions?

### :fire: Extra

This is optional, but you can add any other useful information that would not fit in the other topics.

2021-09-29 20:24 UTC, PedroHLC commented
Assigning @kress95 as this filter is used in WMS' tables.

2021-09-29 21:30 UTC, gregziegan commented
also, feel free to ignore this PR and make your own. i don't care about contribution credit :) just want to use your table filters in my project!

2021-09-30 01:36 UTC, gregziegan commented
also, sorry to expand this any further but there's no issues tab. 

Any ideas on how to solve this? i'd like a column of links / buttons but i'm not sure how to omit one column of filters

![filter-issue](https://user-images.githubusercontent.com/3099999/135371253-287838c6-49de-474b-bc19-a7e150ae81ff.png)

2021-09-30 11:21 UTC, PedroHLC commented
> Any ideas on how to solve this?

I recommend adding something similar to [`unsortable`](https://package.elm-lang.org/packages/PaackEng/paack-ui/latest/UI-Tables-Stateful#unsortable) adapting it to [`UI.Tables.Stateful#Filters`](https://package.elm-lang.org/packages/PaackEng/paack-ui/latest/UI-Tables-Stateful#filtersEmpty).

As we don't have this use-case in any of the in-house applications, I can't merge this (`unfilterable` proposal) right now, but if you do it in a separate PR, I'll merge it when the need appears.

2021-09-30 21:04 UTC, kress95 commented
> Assigning @kress95 as this filter is used in WMS' tables.

Seems fine

2021-09-30 21:04 UTC, kress95 approved these changes

2021-10-01 12:24 UTC, PedroHLC requested changes
You'll need a rebase for the PR to approve. And don't worry we can do the `elm bump` later for you...

2021-10-01 12:24 UTC, PedroHLC commented on elm.json
> +}
Re-add the new line at EOF.
(Your editor should be respecting our `.editorconfig`)

2021-10-01 12:24 UTC, PedroHLC commented on src/UI/DateInput.elm
> +    Internal.RangeDate
Alias to a record is not an opaque type, you can use `{ from : DateInput, to : DateInput }` here.

2021-10-01 12:24 UTC, PedroHLC commented on src/UI/DateInput.elm
> +    Internal.PeriodDate
Alias to a record is not an opaque type, you can use `{ date : DateInput, comparison : PeriodComparison }` here.

2021-10-05 13:58 UTC, PedroHLC commented
@miguelcoba I can't trigger Percy for this PR as it's a branch outside our own repository. Do you have admin powers to force skipping it in this one?

2021-10-05 16:10 UTC, PedroHLC commented
I closed this one in 86f2f64de447e3e3632ce1e0e9a2e33750d4f789, note that I moved it to `UI.Utils.DateInput`

2021-10-05 16:10 UTC, closed without merging