Add inline alerts
PaackEng/paack-ui pull request #311
Opened 2021-09-30 14:17 UTC by sufiyanyusuf

#### :thinking: What?

Inline options for displaying alerts

#### :man_shrugging: Why?

For some use cases, the edge to edge version of the alert doesn't fit nicely in the UI. With this version, we can explore newer placements of the alert component, without covering the entire screen (this is also very useful for showing contextual info sometimes).

#### :pushpin: Jira Issue

Not tracked.

#### :no_good: Blocked by

Nothing.

2021-09-30 14:21 UTC, PedroHLC requested changes
You'll need to change `@docs withGenericIcon` to `@docs withGenericIcon, withInlineStyle`

2021-09-30 14:21 UTC, PedroHLC commented on src/UI/Alert.elm
> +withInlineStyle : Alert msg -> Alert msg
Need `{-| docs -}`

2021-09-30 14:56 UTC, PedroHLC approved these changes

2021-10-01 12:39 UTC, PedroHLC approved these changes

2021-10-01 12:40 UTC, niqt approved these changes

2021-10-04 13:09 UTC, merged