Buttons update
PaackEng/paack-ui pull request #331
Opened 2021-11-18 14:34 UTC by sufiyanyusuf

#### :thinking: What?

Switched on state for buttons

#### :man_shrugging: Why?

For use cases where we need to show something in a 'switched on ' state

#### :pushpin: Jira Issue

DES-127

#### :no_good: Blocked by

Nothing.

#### :clipboard: Pending

Nothing

### :fire: Extra

This is optional, but you can add any other useful information that would not fit in the other topics.

2021-11-18 17:12 UTC, PedroHLC approved these changes
This one already looks good to me!

2021-11-29 14:48 UTC, kress95 approved these changes

2021-11-30 10:36 UTC, niqt approved these changes

2021-11-30 12:20 UTC, PedroHLC requested changes
You'll need to run `elm bump`, and add `switchedOn` to an `@docs` line.

2021-11-30 12:32 UTC, segmentationfaulter approved these changes

2021-11-30 13:55 UTC, kress95 reviewed
Just fix what @PedroHLC asked, otherwise seems alright.

2021-11-30 18:13 UTC, PedroHLC approved these changes

2021-11-30 18:13 UTC, merged