WMS-474 | Add missing stories to Percy
PaackEng/paack-ui pull request #80
Opened 2020-08-26 10:25 UTC by segmentationfaulter

#### :thinking: What?
Adds missing stories to Percy

#### :man_shrugging: Why?
Because they were missing

#### :pushpin: Jira Issue
[WMS-474](https://paacklogistics.atlassian.net/browse/WMS-474)

2020-08-26 10:27 UTC, miguelcoba approved these changes

2020-08-26 17:09 UTC, jouderianjr requested changes
Hey @segmentationfaulter I reviewed the percy snapshots,  I think there are 2 with wrong urls.

2020-08-26 17:09 UTC, jouderianjr commented on cypress/integration/visual-regression.spec.js
> +      cy.visit('/#Basics/TextField/Full&20Width')
I think this url is wrong, the correspondent Percy image

2020-08-27 09:10 UTC, jouderianjr approved these changes

2020-08-27 09:56 UTC, merged